// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAO4N2lx8DuaBTLhTpMXijOrBInpcyusU',
    appId: '1:789562608602:web:2ae56da1f0d41d2a218ee3',
    messagingSenderId: '789562608602',
    projectId: 'flutter-freecodecamp-69df3',
    authDomain: 'flutter-freecodecamp-69df3.firebaseapp.com',
    storageBucket: 'flutter-freecodecamp-69df3.appspot.com',
    measurementId: 'G-38ZSP6RTV1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAYUgHyUE5OU3bT4ChhSFaWloLH05a5U7g',
    appId: '1:789562608602:android:2ae76b362f3c1c65218ee3',
    messagingSenderId: '789562608602',
    projectId: 'flutter-freecodecamp-69df3',
    storageBucket: 'flutter-freecodecamp-69df3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBVS4-Wy6Mn3bqyI-5VxbR7Tty-db35LbY',
    appId: '1:789562608602:ios:6c163951c513d2c9218ee3',
    messagingSenderId: '789562608602',
    projectId: 'flutter-freecodecamp-69df3',
    storageBucket: 'flutter-freecodecamp-69df3.appspot.com',
    iosClientId: '789562608602-0v3fl36vr10ki6e9g2calumpo73e97fs.apps.googleusercontent.com',
    iosBundleId: 'se.pixolity.mynotes',
  );
}
